In [1]:
# Import modules
import matplotlib.pyplot as plt
import pandas as pd
#import geopandas as gpd
from census import Census
from us import states

In [2]:
# Set API key
# Took API key out for privacy, must reinsert key to rerun the code
c = Census("87e3b56dbbf336c23ff91db21cf61a120b7863f0")

In [3]:
variables = ("B01003_001E,B02001_002E,B02001_003E,B02001_005E,B03001_003E,B02001_004E,B03002_003E,B03002_004E,B03002_005E,B03002_006E,B03002_007E,B03002_008E,B03002_009E,B03002_013E,B03002_014E,B03002_015E,B03002_016E,B03002_017E,B03002_018E,B03002_019E,B01002_001E,B01001_002E,B01001_026E,B19326_001E,B17001_002E,B27011_003E,B25105_001E,B08008_003E,B25033_008E,B25008_002E,B25008_001E,B25001_001E,B09002_001E,B19123_001E,B99051_002E,B99051_005E,B16010_002E,B16010_015E,B16010_028E,B16010_041E")

In [4]:
ca_census = c.acs5.state_county_tract(fields = ('NAME', variables),
                                      state_fips = states.CA.fips,
                                      county_fips = "037",
                                      tract = '*',
                                      year = 2020)
census_df=pd.DataFrame(ca_census)
census_df

,NAME,B01003_001E,B02001_002E,B02001_003E,B02001_005E,B03001_003E,B02001_004E,B03002_003E,B03002_004E,B03002_005E,...,B19123_001E,B99051_002E,B99051_005E,B16010_002E,B16010_015E,B16010_028E,B16010_041E,state,county,tract
0,"Census Tract 1997, Los Angeles County, California",3006.0,903.0,112.0,426.0,2043.0,35.0,401.0,112.0,0.0,...,687.0,1661.0,1345.0,863.0,340.0,396.0,709.0,06,037,199700
1,"Census Tract 1998.01, Los Angeles County, Cali...",3618.0,482.0,18.0,1092.0,2500.0,306.0,23.0,18.0,0.0,...,791.0,2048.0,1570.0,997.0,504.0,469.0,157.0,06,037,199801
2,"Census Tract 1998.02, Los Angeles County, Cali...",2419.0,384.0,0.0,1328.0,1062.0,0.0,51.0,0.0,0.0,...,493.0,994.0,1425.0,810.0,438.0,206.0,262.0,06,037,199802
3,"Census Tract 1999, Los Angeles County, California",2687.0,803.0,7.0,437.0,2202.0,0.0,41.0,7.0,0.0,...,521.0,1531.0,1156.0,809.0,541.0,266.0,219.0,06,037,199900
4,"Census Tract 2011.10, Los Angeles County, Cali...",2203.0,781.0,76.0,345.0,1562.0,30.0,243.0,67.0,0.0,...,524.0,1456.0,747.0,448.0,317.0,315.0,480.0,06,037,201110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2493,"Census Tract 8005.06, Los Angeles County, Cali...",3274.0,2586.0,33.0,226.0,233.0,21.0,2488.0,33.0,0.0,...,1103.0,2663.0,611.0,33.0,129.0,643.0,1952.0,06,037,800506
2494,"Census Tract 9001.02, Los Angeles County, Cali...",719.0,488.0,18.0,13.0,342.0,18.0,303.0,13.0,4.0,...,166.0,582.0,137.0,250.0,127.0,121.0,48.0,06,037,900102
2495,"Census Tract 9001.03, Los Angeles County, Cali...",6281.0,5616.0,388.0,14.0,3503.0,0.0,2244.0,388.0,0.0,...,1438.0,5981.0,300.0,942.0,1427.0,1023.0,455.0,06,037,900103
2496,"Census Tract 9001.04, Los Angeles County, Cali...",5665.0,3477.0,227.0,26.0,3595.0,6.0,1687.0,218.0,0.0,...,1283.0,4936.0,729.0,1101.0,1108.0,1057.0,260.0,06,037,900104
2497,"Census Tract 9003.01, Los Angeles County, Cali...",4610.0,2529.0,1099.0,336.0,2226.0,0.0,824.0,1099.0,0.0,...,782.0,4120.0,490.0,502.0,720.0,525.0,231.0,06,037,900301

In [5]:
# Re_labeled the columns.
census_df = census_df.rename({'B01003_001E':'total_pop','B02001_002E':'pop_white','B02001_003E':'pop_black','B02001_005E':'pop_asian','B03001_003E':'pop_hispanic','B02001_004E':'pop_native_amer','B03002_003E':'pop_not_hisp_white','B03002_004E':'pop_not_hisp_black','B03002_005E':'pop_not_hisp_na','B03002_006E':'pop_not_hisp_asian','B03002_007E':'pop_not_hisp_nh_pi','B03002_008E':'pop_not_hisp_other','B03002_009E':'pop_not_hisp_two_more','B03002_013E':'pop_hisp_white','B03002_014E':'B03002_014','B03002_015E':'pop_hisp_na','B03002_016E':'pop_hisp_asian','B03002_017E':'pop_hisp_nh_pi','B03002_018E':'pop_hisp_other','B03002_019E':'pop_hisp_two_more','B01002_001E':'med_age','B01001_002E':'pop_male','B01001_026E':'pop_female','B19326_001E':'med_income','B17001_002E':'pop_below_poverty','B27011_003E':'pop_employed','B25105_001E':'month_housing_costs','B08008_003E':'pop_work_out_res_area','B25033_008E':'pop_rented','B25008_002E':'pop_owned','B25008_001E':'pop_occupied','B25001_001E':'total_hu','B09002_001E':'pop_under_18','B19123_001E':'total_families','B99051_002E':'pop_native_born','B99051_005E':'pop_foreign_born','B16010_002E':'pop_educ_lt_hs','B16010_015E':'pop_educ_hs','B16010_028E':'pop_educ_some_col','B16010_041E':'pop_educ_mt_ba'
}, axis=1) 
census_df

,NAME,total_pop,pop_white,pop_black,pop_asian,pop_hispanic,pop_native_amer,pop_not_hisp_white,pop_not_hisp_black,pop_not_hisp_na,...,total_families,pop_native_born,pop_foreign_born,pop_educ_lt_hs,pop_educ_hs,pop_educ_some_col,pop_educ_mt_ba,state,county,tract
0,"Census Tract 1997, Los Angeles County, California",3006.0,903.0,112.0,426.0,2043.0,35.0,401.0,112.0,0.0,...,687.0,1661.0,1345.0,863.0,340.0,396.0,709.0,06,037,199700
1,"Census Tract 1998.01, Los Angeles County, Cali...",3618.0,482.0,18.0,1092.0,2500.0,306.0,23.0,18.0,0.0,...,791.0,2048.0,1570.0,997.0,504.0,469.0,157.0,06,037,199801
2,"Census Tract 1998.02, Los Angeles County, Cali...",2419.0,384.0,0.0,1328.0,1062.0,0.0,51.0,0.0,0.0,...,493.0,994.0,1425.0,810.0,438.0,206.0,262.0,06,037,199802
3,"Census Tract 1999, Los Angeles County, California",2687.0,803.0,7.0,437.0,2202.0,0.0,41.0,7.0,0.0,...,521.0,1531.0,1156.0,809.0,541.0,266.0,219.0,06,037,199900
4,"Census Tract 2011.10, Los Angeles County, Cali...",2203.0,781.0,76.0,345.0,1562.0,30.0,243.0,67.0,0.0,...,524.0,1456.0,747.0,448.0,317.0,315.0,480.0,06,037,201110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2493,"Census Tract 8005.06, Los Angeles County, Cali...",3274.0,2586.0,33.0,226.0,233.0,21.0,2488.0,33.0,0.0,...,1103.0,2663.0,611.0,33.0,129.0,643.0,1952.0,06,037,800506
2494,"Census Tract 9001.02, Los Angeles County, Cali...",719.0,488.0,18.0,13.0,342.0,18.0,303.0,13.0,4.0,...,166.0,582.0,137.0,250.0,127.0,121.0,48.0,06,037,900102
2495,"Census Tract 9001.03, Los Angeles County, Cali...",6281.0,5616.0,388.0,14.0,3503.0,0.0,2244.0,388.0,0.0,...,1438.0,5981.0,300.0,942.0,1427.0,1023.0,455.0,06,037,900103
2496,"Census Tract 9001.04, Los Angeles County, Cali...",5665.0,3477.0,227.0,26.0,3595.0,6.0,1687.0,218.0,0.0,...,1283.0,4936.0,729.0,1101.0,1108.0,1057.0,260.0,06,037,900104
2497,"Census Tract 9003.01, Los Angeles County, Cali...",4610.0,2529.0,1099.0,336.0,2226.0,0.0,824.0,1099.0,0.0,...,782.0,4120.0,490.0,502.0,720.0,525.0,231.0,06,037,900301

In [6]:
census_df.columns

Index(['NAME', 'total_pop', 'pop_white', 'pop_black', 'pop_asian',
       'pop_hispanic', 'pop_native_amer', 'pop_not_hisp_white',
       'pop_not_hisp_black', 'pop_not_hisp_na', 'pop_not_hisp_asian',
       'pop_not_hisp_nh_pi', 'pop_not_hisp_other', 'pop_not_hisp_two_more',
       'pop_hisp_white', 'B03002_014', 'pop_hisp_na', 'pop_hisp_asian',
       'pop_hisp_nh_pi', 'pop_hisp_other', 'pop_hisp_two_more', 'med_age',
       'pop_male', 'pop_female', 'med_income', 'pop_below_poverty',
       'pop_employed', 'month_housing_costs', 'pop_work_out_res_area',
       'pop_rented', 'pop_owned', 'pop_occupied', 'total_hu', 'pop_under_18',
       'total_families', 'pop_native_born', 'pop_foreign_born',
       'pop_educ_lt_hs', 'pop_educ_hs', 'pop_educ_some_col', 'pop_educ_mt_ba',
       'state', 'county', 'tract'],
      dtype='object')

In [7]:
census_df.head()

,NAME,total_pop,pop_white,pop_black,pop_asian,pop_hispanic,pop_native_amer,pop_not_hisp_white,pop_not_hisp_black,pop_not_hisp_na,...,total_families,pop_native_born,pop_foreign_born,pop_educ_lt_hs,pop_educ_hs,pop_educ_some_col,pop_educ_mt_ba,state,county,tract
0,"Census Tract 1997, Los Angeles County, California",3006.0,903.0,112.0,426.0,2043.0,35.0,401.0,112.0,0.0,...,687.0,1661.0,1345.0,863.0,340.0,396.0,709.0,06,037,199700
1,"Census Tract 1998.01, Los Angeles County, Cali...",3618.0,482.0,18.0,1092.0,2500.0,306.0,23.0,18.0,0.0,...,791.0,2048.0,1570.0,997.0,504.0,469.0,157.0,06,037,199801
2,"Census Tract 1998.02, Los Angeles County, Cali...",2419.0,384.0,0.0,1328.0,1062.0,0.0,51.0,0.0,0.0,...,493.0,994.0,1425.0,810.0,438.0,206.0,262.0,06,037,199802
3,"Census Tract 1999, Los Angeles County, California",2687.0,803.0,7.0,437.0,2202.0,0.0,41.0,7.0,0.0,...,521.0,1531.0,1156.0,809.0,541.0,266.0,219.0,06,037,199900
4,"Census Tract 2011.10, Los Angeles County, Cali...",2203.0,781.0,76.0,345.0,1562.0,30.0,243.0,67.0,0.0,...,524.0,1456.0,747.0,448.0,317.0,315.0,480.0,06,037,201110

In [8]:
!ls

2020_cleaning_arrests.ipynb    Merging_Data.ipynb
Census_Data_Extraction.ipynb   README.md
Census_by_Tract.ipynb          RF_ML.ipynb
Census_by_Tract_new.ipynb      Resources
Cleaned_Data                   Substance_Abuse_Programs.ipynb
Images                         arrests_2020_zip.ipynb
KL.ipynb                       census_api_call-Copy1.ipynb
LAPD stations CD.ipynb         cleaning_data_for_tables.ipynb
LAPDCLEAN.ipynb                encoding data_NN.ipynb
Mental_Health_Programs.ipynb   sql_schema.txt
Mental_health_centers.ipynb

In [9]:
census_tract=pd.read_csv('Resources/ZIP_TRACT_122020.csv', dtype='object')
census_tract.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172245 entries, 0 to 172244
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ZIP     172245 non-null  object
 1   TRACT   172245 non-null  object
dtypes: object(2)
memory usage: 2.6+ MB

In [10]:
census_df['census_tract']=census_df['state']+census_df['county']+census_df['tract']
census_df['census_tract']

0       06037199700
1       06037199801
2       06037199802
3       06037199900
4       06037201110
           ...
2493    06037800506
2494    06037900102
2495    06037900103
2496    06037900104
2497    06037900301
Name: census_tract, Length: 2498, dtype: object

In [11]:
census_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2498 entries, 0 to 2497
Data columns (total 45 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NAME                   2498 non-null   object
 1   total_pop              2498 non-null   float64
 2   pop_white              2498 non-null   float64
 3   pop_black              2498 non-null   float64
 4   pop_asian              2498 non-null   float64
 5   pop_hispanic           2498 non-null   float64
 6   pop_native_amer        2498 non-null   float64
 7   pop_not_hisp_white     2498 non-null   float64
 8   pop_not_hisp_black     2498 non-null   float64
 9   pop_not_hisp_na        2498 non-null   float64
 10  pop_not_hisp_asian     2498 non-null   float64
 11  pop_not_hisp_nh_pi     2498 non-null   float64
 12  pop_not_hisp_other     2498 non-null   float64
 13  pop_not_hisp_two_more  2498 non-null   float64
 14  pop_hisp_white         2498 non-null   float64
 15  B03002_014             2498 non-null   float64
 16  pop_hisp_na            2498 non-null   float64
 17  pop_hisp_asian         2498 non-null   float64
 18  pop_hisp_nh_pi         2498 non-null   float64
 19  pop_hisp_other         2498 non-null   float64
 20  pop_hisp_two_more      2498 non-null   float64
 21  med_age                2498 non-null   float64
 22  pop_male               2498 non-null   float64
 23  pop_female             2498 non-null   float64
 24  med_income             2498 non-null   float64
 25  pop_below_poverty      2498 non-null   float64
 26  pop_employed           2498 non-null   float64
 27  month_housing_costs    2498 non-null   float64
 28  pop_work_out_res_area  2498 non-null   float64
 29  pop_rented             2498 non-null   float64
 30  pop_owned              2498 non-null   float64
 31  pop_occupied           2498 non-null   float64
 32  total_hu               2498 non-null   float64
 33  pop_under_18           2498 non-null   float64
 34  total_families         2498 non-null   float64
 35  pop_native_born        2498 non-null   float64
 36  pop_foreign_born       2498 non-null   float64
 37  pop_educ_lt_hs         2498 non-null   float64
 38  pop_educ_hs            2498 non-null   float64
 39  pop_educ_some_col      2498 non-null   float64
 40  pop_educ_mt_ba         2498 non-null   float64
 41  state                  2498 non-null   object
 42  county                 2498 non-null   object
 43  tract                  2498 non-null   object
 44  census_tract           2498 non-null   object
dtypes: float64(40), object(5)
memory usage: 878.3+ KB

In [12]:
merged_df=pd.merge(census_df, census_tract, left_on='census_tract', right_on='TRACT')
merged_df.head()

,NAME,total_pop,pop_white,pop_black,pop_asian,pop_hispanic,pop_native_amer,pop_not_hisp_white,pop_not_hisp_black,pop_not_hisp_na,...,pop_educ_lt_hs,pop_educ_hs,pop_educ_some_col,pop_educ_mt_ba,state,county,tract,census_tract,ZIP,TRACT
0,"Census Tract 1997, Los Angeles County, California",3006.0,903.0,112.0,426.0,2043.0,35.0,401.0,112.0,0.0,...,863.0,340.0,396.0,709.0,06,037,199700,06037199700,90031,06037199700
1,"Census Tract 1999, Los Angeles County, California",2687.0,803.0,7.0,437.0,2202.0,0.0,41.0,7.0,0.0,...,809.0,541.0,266.0,219.0,06,037,199900,06037199900,90031,06037199900
2,"Census Tract 1999, Los Angeles County, California",2687.0,803.0,7.0,437.0,2202.0,0.0,41.0,7.0,0.0,...,809.0,541.0,266.0,219.0,06,037,199900,06037199900,90033,06037199900
3,"Census Tract 2011.10, Los Angeles County, Cali...",2203.0,781.0,76.0,345.0,1562.0,30.0,243.0,67.0,0.0,...,448.0,317.0,315.0,480.0,06,037,201110,06037201110,90032,06037201110
4,"Census Tract 2011.20, Los Angeles County, Cali...",4043.0,1144.0,82.0,377.0,3182.0,37.0,339.0,71.0,0.0,...,764.0,426.0,621.0,735.0,06,037,201120,06037201120,90032,06037201120

In [14]:
merged_df.to_csv('Resources/census_data_merged.csv', index=False)

In [21]:
len(merged_df)

3414