In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Import Arrest CSV
arrest_file = pd.read_csv('Cleaned_Data/la_arrests_2020_w_zip.csv')
arrest_df = pd.DataFrame(arrest_file)
arrest_df

,Arrest Date,Area Name,Age,Sex Code,Descent Code,Charge Group Description,Charge Description,Disposition Description,LAT,LON,Location,Booking Location,Zip_Codes
0,2020-05-10,77th Street,22,M,B,Weapon (carry/poss),CARRY LOADED F/ARM PRSON/HEH PUBLIC PLACE,DISTRICT ATTORNEY REJECT,33.9674,-118.2652,POINT (-118.2652 33.9674),77TH ST,90003
1,2020-05-29,Pacific,30,M,B,Narcotic Drug Laws,MAINTAIN PLACE TO SELL CONTROLLED SUBS,CITY ATTORNEY REJECT,34.0249,-118.3960,POINT (-118.396 34.0249),PACIFIC,90066
2,2020-07-28,77th Street,29,M,H,Vehicle Theft,GRAND THEFT AUTO/HORSE/ETC,DISTRICT ATTORNEY REJECT,33.9892,-118.2827,POINT (-118.2827 33.9892),77TH ST,90003
3,2020-11-25,77th Street,40,M,B,Weapon (carry/poss),POSS F/ARM BY CONVICTED FELON/ADDICT/ETC,849(B)(1) PC/TECHNICAL ARREST,33.9764,-118.2892,POINT (-118.2892 33.9764),77TH ST,90003
4,2020-04-04,77th Street,30,M,H,Burglary,BURGLARY,FELONY COMPLAINT FILED,33.9611,-118.2917,POINT (-118.2917 33.9611),77TH ST,90003
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48389,2020-09-26,Foothill,43,M,H,Driving Under Influence,DUI OF ANY DRUG,MISDEMEANOR COMPLAINT FILED,34.2554,-118.3934,POINT (-118.3934 34.2554),VALLEY - JAIL DIV,91331
48390,2020-04-15,Olympic,32,F,H,Larceny,PETTY THEFT,MISDEMEANOR COMPLAINT FILED,34.0526,-118.2916,POINT (-118.2916 34.0526),METRO - JAIL DIVISION,90006
48391,2020-12-13,Hollenbeck,32,M,H,Vehicle Theft,GRAND THEFT AUTO/HORSE/ETC,CITY ATTORNEY REJECT,34.0141,-118.1950,POINT (-118.195 34.0141),METRO - JAIL DIVISION,90033
48392,2020-08-29,Newton,35,F,H,Aggravated Assault,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,FELONY COMPLAINT FILED,34.0226,-118.2660,POINT (-118.266 34.0226),77TH ST,90011
48393,2020-11-01,Van Nuys,31,M,H,Miscellaneous Other Violations,ARSON OF STRUCTURE OR FOREST LAND,849(B)(1) PC/TECHNICAL ARREST,34.1867,-118.4487,POINT (-118.4487 34.1867),VALLEY - JAIL DIV,91401

In [3]:
pd_file = pd.read_csv('Cleaned_Data/LAPD_Stats.csv')
pd_df = pd.DataFrame(pd_file)
pd_df

,Unnamed: 0,OBJECTID,DIVISION,PREC,LOCATION,ZIP,LONG,LAT
0,0,1,HARBOR,5,2175 JOHN S. GIBSON BLVD.,90731,-118.289242,33.757661
1,1,2,SOUTHEAST,18,145 W. 108TH ST.,90061,-118.275394,33.938627
2,2,3,77TH STREET,12,7600 S. BROADWAY,90003,-118.277670,33.970307
3,3,4,PACIFIC,14,12312 CULVER BLVD.,90066,-118.419842,33.991655
4,4,5,SOUTHWEST,3,1546 MARTIN LUTHER KING JR. BLVD.,90062,-118.305142,34.010575
5,5,6,NEWTON,13,3400 S. CENTRAL AVE.,90011,-118.256119,34.012356
6,6,7,CENTRAL,1,251 E. 6TH ST.,90014,-118.247294,34.044019
7,7,8,WEST LOS ANGELES,8,1663 BUTLER AVE.,90025,-118.450780,34.043777
8,8,9,HOLLENBECK,4,2111 E. 1ST ST.,90033,-118.213068,34.045009
9,9,10,WILSHIRE,7,4861 VENICE BLVD.,90019,-118.342830,34.046748
10,10,11,OLYMPIC,20,1130 S. VERMONT AVE.,90006,-118.291176,34.050209
11,11,12,RAMPART,2,1401 W. 6TH ST.,90017,-118.266980,34.056690
12,12,13,HOLLYWOOD,6,1358 N. WILCOX AVE.,90028,-118.330669,34.095833
13,13,14,NORTHEAST,11,3353 SAN FERNANDO RD.,90065,-118.249414,34.119201
14,14,15,NORTH HOLLYWOOD,15,11640 BURBANK BLVD.,91601,-118.385859,34.171694
15,15,16,VAN NUYS,9,6240 SYLMAR AVE.,91401,-118.445226,34.183743
16,16,17,WEST VALLEY,10,19020 VANOWEN ST.,91335,-118.547454,34.193397
17,17,18,TOPANGA,21,21501 SCHOENBORN ST.,91304,-118.599637,34.221377
18,18,19,FOOTHILL,16,12760 OSBORNE ST.,91331,-118.410417,34.253091
19,19,20,DEVONSHIRE,17,10250 ETIWANDA AVE.,91324,-118.531373,34.256969
20,20,21,MISSION,19,11121 N. SEPULVEDA BLVD.,91345,-118.468198,34.272979

In [4]:
# Create new DataFrame w/ police and arrest csv
police_arrests = arrest_df.merge(pd_df,left_on='Zip_Codes', right_on='ZIP')
police_arrests.head()

,Arrest Date,Area Name,Age,Sex Code,Descent Code,Charge Group Description,Charge Description,Disposition Description,LAT_x,LON,...,Booking Location,Zip_Codes,Unnamed: 0,OBJECTID,DIVISION,PREC,LOCATION,ZIP,LONG,LAT_y
0,2020-05-10,77th Street,22,M,B,Weapon (carry/poss),CARRY LOADED F/ARM PRSON/HEH PUBLIC PLACE,DISTRICT ATTORNEY REJECT,33.9674,-118.2652,...,77TH ST,90003,2,3,77TH STREET,12,7600 S. BROADWAY,90003,-118.27767,33.970307
1,2020-07-28,77th Street,29,M,H,Vehicle Theft,GRAND THEFT AUTO/HORSE/ETC,DISTRICT ATTORNEY REJECT,33.9892,-118.2827,...,77TH ST,90003,2,3,77TH STREET,12,7600 S. BROADWAY,90003,-118.27767,33.970307
2,2020-11-25,77th Street,40,M,B,Weapon (carry/poss),POSS F/ARM BY CONVICTED FELON/ADDICT/ETC,849(B)(1) PC/TECHNICAL ARREST,33.9764,-118.2892,...,77TH ST,90003,2,3,77TH STREET,12,7600 S. BROADWAY,90003,-118.27767,33.970307
3,2020-04-04,77th Street,30,M,H,Burglary,BURGLARY,FELONY COMPLAINT FILED,33.9611,-118.2917,...,77TH ST,90003,2,3,77TH STREET,12,7600 S. BROADWAY,90003,-118.27767,33.970307
4,2020-11-11,77th Street,30,M,H,Receive Stolen Property,OWN/OPERATE A 'CHOP SHOP',DISTRICT ATTORNEY REJECT,33.9717,-118.2813,...,77TH ST,90003,2,3,77TH STREET,12,7600 S. BROADWAY,90003,-118.27767,33.970307

In [5]:
police_arrests.count()

Arrest Date                 48394
Area Name                   48394
Age                         48394
Sex Code                    48394
Descent Code                48394
Charge Group Description    48394
Charge Description          48394
Disposition Description     48394
LAT_x                       48394
LON                         48394
Location                    48394
Booking Location            48394
Zip_Codes                   48394
Unnamed: 0                  48394
OBJECTID                    48394
DIVISION                    48394
PREC                        48394
LOCATION                    48394
ZIP                         48394
LONG                        48394
LAT_y                       48394
dtype: int64

In [7]:
mhr_df = pd.read_csv('Resources/mhp_mhc_sap.csv')
mhr_df.head()

,x,y,objectid,cat1,cat2,name,city,state,post_id,zip,latitude,longitude,date_updated,point_x,point_y,program_type
0,-118.043903,34.571358,72440,Health and Mental Health,Mental Health Centers,"JWCH Institute, Inc. â€“ Wesley Palmdale East",Palmdale,CA,2007348,93552,34.571358,-118.043903,2020/02/19 11:37:40+00,6.548454e+06,2.030312e+06,General Mental Health Resource
1,-118.137915,34.582571,72218,Health and Mental Health,Mental Health Centers,TESSIE CLEVELAND COM SERVICES,PALMDALE,CA,2005585,93551,34.582571,-118.137915,2018/03/06 09:13:11+00,6.520159e+06,2.034418e+06,General Mental Health Resource
2,-118.147850,34.609340,71781,Health and Mental Health,Mental Health Centers,CHILD AND FAM GUIDANCE CENTER-PALMDALE,PALMDALE,CA,1000153,93551,34.609340,-118.147850,2017/02/08 10:49:24+00,6.517183e+06,2.044164e+06,General Mental Health Resource
3,-118.140270,34.583760,71953,Health and Mental Health,Mental Health Centers,OPTIMIST YOUTH HOMES-PALMDALE,PALMDALE,CA,1000335,93551,34.583760,-118.140270,2016/05/30 18:53:23+00,6.519451e+06,2.034852e+06,General Mental Health Resource
4,-118.100880,34.579980,71842,Health and Mental Health,Mental Health Centers,PALMDALE DISCOVERY CENTER,PALMDALE,CA,1000221,93550,34.579980,-118.100880,2016/05/30 18:53:23+00,6.531305e+06,2.033462e+06,General Mental Health Resource

In [13]:
final_data = police_arrests.merge(mhr_df,left_on='Zip_Codes', right_on='zip')
final_data.head()

,Arrest Date,Area Name,Age,Sex Code,Descent Code,Charge Group Description,Charge Description,Disposition Description,LAT_x,LON,...,city,state,post_id,zip,latitude,longitude,date_updated,point_x,point_y,program_type
0,2020-05-10,77th Street,22,M,B,Weapon (carry/poss),CARRY LOADED F/ARM PRSON/HEH PUBLIC PLACE,DISTRICT ATTORNEY REJECT,33.9674,-118.2652,...,LOS ANGELES,CA,1000336,90003,33.96397,-118.26934,2016/05/30 18:53:23+00,6.479998e+06,1.809378e+06,General Mental Health Resource
1,2020-05-10,77th Street,22,M,B,Weapon (carry/poss),CARRY LOADED F/ARM PRSON/HEH PUBLIC PLACE,DISTRICT ATTORNEY REJECT,33.9674,-118.2652,...,LOS ANGELES,CA,1000144,90003,33.94843,-118.26602,2018/04/27 13:44:19+00,6.480990e+06,1.803720e+06,General Mental Health Resource
2,2020-05-10,77th Street,22,M,B,Weapon (carry/poss),CARRY LOADED F/ARM PRSON/HEH PUBLIC PLACE,DISTRICT ATTORNEY REJECT,33.9674,-118.2652,...,LOS ANGELES,CA,1000430,90003,33.98846,-118.26863,2018/05/18 08:26:16+00,6.480237e+06,1.818290e+06,General Mental Health Resource
3,2020-05-10,77th Street,22,M,B,Weapon (carry/poss),CARRY LOADED F/ARM PRSON/HEH PUBLIC PLACE,DISTRICT ATTORNEY REJECT,33.9674,-118.2652,...,LOS ANGELES,CA,1000386,90003,33.94175,-118.28282,2018/05/17 13:04:06+00,6.475888e+06,1.801303e+06,General Mental Health Resource
4,2020-05-10,77th Street,22,M,B,Weapon (carry/poss),CARRY LOADED F/ARM PRSON/HEH PUBLIC PLACE,DISTRICT ATTORNEY REJECT,33.9674,-118.2652,...,LOS ANGELES,CA,1000347,90003,33.97262,-118.27823,2018/05/17 10:47:10+00,6.477311e+06,1.812533e+06,General Mental Health Resource

In [14]:
final_data.count()

Arrest Date                 337384
Area Name                   337384
Age                         337384
Sex Code                    337384
Descent Code                337384
Charge Group Description    337384
Charge Description          337384
Disposition Description     337384
LAT_x                       337384
LON                         337384
Location                    337384
Booking Location            337384
Zip_Codes                   337384
Unnamed: 0                  337384
OBJECTID                    337384
DIVISION                    337384
PREC                        337384
LOCATION                    337384
ZIP                         337384
LONG                        337384
LAT_y                       337384
x                           337384
y                           337384
objectid                    337384
cat1                        337384
cat2                        337384
name                        337384
city                        337384
state                       337384
post_id                     337384
zip                         337384
latitude                    337384
longitude                   337384
date_updated                337384
point_x                     337384
point_y                     337384
program_type                337384
dtype: int64

In [15]:
final_data = final_data.drop(columns=['Unnamed: 0','OBJECTID'])
final_data.count()

Arrest Date                 337384
Area Name                   337384
Age                         337384
Sex Code                    337384
Descent Code                337384
Charge Group Description    337384
Charge Description          337384
Disposition Description     337384
LAT_x                       337384
LON                         337384
Location                    337384
Booking Location            337384
Zip_Codes                   337384
DIVISION                    337384
PREC                        337384
LOCATION                    337384
ZIP                         337384
LONG                        337384
LAT_y                       337384
x                           337384
y                           337384
objectid                    337384
cat1                        337384
cat2                        337384
name                        337384
city                        337384
state                       337384
post_id                     337384
zip                         337384
latitude                    337384
longitude                   337384
date_updated                337384
point_x                     337384
point_y                     337384
program_type                337384
dtype: int64

In [16]:
final_data.dtypes

Arrest Date                  object
Area Name                    object
Age                           int64
Sex Code                     object
Descent Code                 object
Charge Group Description     object
Charge Description           object
Disposition Description      object
LAT_x                       float64
LON                         float64
Location                     object
Booking Location             object
Zip_Codes                     int64
DIVISION                     object
PREC                          int64
LOCATION                     object
ZIP                           int64
LONG                        float64
LAT_y                       float64
x                           float64
y                           float64
objectid                      int64
cat1                         object
cat2                         object
name                         object
city                         object
state                        object
post_id                       int64
zip                           int64
latitude                    float64
longitude                   float64
date_updated                 object
point_x                     float64
point_y                     float64
program_type                 object
dtype: object

In [18]:
ml_cat_1 = final_data.dtypes[final_data.dtypes=='object'].index.tolist()
ml_cat_2 = final_data.dtypes[final_data.dtypes=='int64'].index.tolist()
ml_cat_3 = final_data.dtypes[final_data.dtypes=='float64'].index.tolist()
ml_cat = ml_cat_1 + ml_cat_2 + ml_cat_3

In [19]:
final_data[ml_cat].nunique()

Arrest Date                   366
Area Name                      18
Sex Code                        2
Descent Code                   15
Charge Group Description       27
Charge Description            692
Disposition Description        17
Location                    17164
Booking Location               20
DIVISION                       18
LOCATION                       18
cat1                            1
cat2                            2
name                          117
city                           21
state                           1
date_updated                   99
program_type                    3
Age                            88
Zip_Codes                      18
PREC                           18
ZIP                            18
objectid                      129
post_id                       122
zip                            18
LAT_x                        3681
LON                          3658
LONG                           18
LAT_y                          18
x                             103
y                             103
latitude                      103
longitude                     102
point_x                       102
point_y                       103
dtype: int64

In [60]:
import sqlalchemy as sql
from config import password

In [70]:
sql_connection=(f'postgresql://postgres:{password}@aws.c15kzfb4ahnm.us-east-2.rds.amazonaws.com:5432/postgres')

In [71]:
engine=sql.create_engine(sql_connection)

In [72]:
engine.table_names()

C:\Users\erica\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  """Entry point for launching an IPython kernel.

[]

In [73]:
final_data.to_sql('crime_dataset',con=engine,if_exists='replace',index=False)

In [74]:
engine.table_names()

C:\Users\erica\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  """Entry point for launching an IPython kernel.

['crime_dataset']